version: '3.8'

networks:
  pistar-net:
    driver: bridge

volumes:
  pistar-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./config
  pistar-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs

services:
  mmdvmhost:
    image: ghcr.io/mw0mwz/pi-star_docker/mmdvmhost:latest
    container_name: mmdvmhost
    privileged: true
    devices:
      # USB devices (hotham, zu3m, etc)
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyUSB2:/dev/ttyUSB2
      - /dev/ttyUSB3:/dev/ttyUSB3
      # Pi GPIO UART
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/ttyAMA1:/dev/ttyAMA1
      # Alternative Pi UART names
      - /dev/serial0:/dev/serial0
      - /dev/serial1:/dev/serial1
      # Pi GPIO access
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip1:/dev/gpiochip1
      # I2C devices
      - /dev/i2c-0:/dev/i2c-0
      - /dev/i2c-1:/dev/i2c-1
      # SPI devices  
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
      - /dev/spidev1.0:/dev/spidev1.0
      - /dev/spidev1.1:/dev/spidev1.1
    volumes:
      - pistar-config:/opt/pi-star/etc:ro # Read-Only
      - pistar-logs:/opt/pi-star/log      # Read-Write
      # GPIO control for Pi
      - /sys/class/gpio:/sys/class/gpio
    networks:
      - pistar-net
    restart: unless-stopped

  dmrgateway:
    image: ghcr.io/mw0mwz/pi-star_docker/dmrgateway:latest
    depends_on:
      - mmdvmhost
    volumes:
      - pistar-config:/opt/pi-star/etc:ro # Read-Only
      - pistar-logs:/opt/pi-star/log      # Read-Write
    networks:
      - pistar-net

  dmrgateway:
    image: ghcr.io/mw0mwz/pi-star_docker/dmrgateway:latest
    container_name: dmrgateway
    depends_on:
      - mmdvmhost
    volumes:
      - pistar-config:/opt/pi-star/etc:ro # Read-Only
      - pistar-logs:/opt/pi-star/log      # Read-Write
    networks:
      - pistar-net
    restart: unless-stopped

  dashboard:
    image: ghcr.io/mw0mwz/pi-star_docker/dashboard:latest
    ports:
      - "8080:8080"
    volumes:
      - pistar-config:/opt/pi-star/etc    # Read-Write for dashboard
      - pistar-logs:/opt/pi-star/log:ro   # Read-Only for dashboard
    networks:
      - pistar-net
  