name: Build Multi-Platform Docker Images

on:
  push:
    branches: [main]
    paths: ['mmdvmhost/**']
  pull_request:
    branches: [main]
    paths: ['mmdvmhost/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./mmdvmhost
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/mmdvmhost:latest
            ghcr.io/${{ github.repository_owner }}/mmdvmhost:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

